default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('MAX_THREADS') { 5 } %>
  database: test1
  username:  postgres
  password:  postgres
  host: postgres
  port: 5432
development:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
production:
  <<: *default