# Build the container
build:
	docker build -t produce-service .

# Run container
up:
	docker run --name produce-service produce-service;

# Stop and remove a running container
stop:
	docker stop produce-service; docker rm produce-service