version: '3.4'

x-backend-app: &backend-app
  build:
    context: .
    dockerfile: Dockerfile
  restart: on-failure
  networks:
      - grpc-network
  stdin_open: true
  user: "ruby"
  tty: true

services:
  postgres:
    image: postgres:13.1
    restart: always
    networks:
      - grpc-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data

  backend:
    <<: *backend-app
    entrypoint: ./docker-entrypoint.sh
    command: ruby ./app/application.rb
    depends_on:
      - postgres
volumes:
  db-volume:

networks:
  grpc-network:
    driver: bridge