default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('MAX_THREADS') { 5 } %>
  database: <%= ENV['DATABASE_NAME'] %>
  username:  <%= ENV['DATABASE_USER'] %>
  password:  <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['PORT'] %>
development:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
production:
  <<: *default