# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.0.3'

# A PostgreSQL client library for Ruby
gem 'pg'

# A gem to use Rails Database Migrations in non Rails projects
gem "standalone_migrations", "~> 6.1"

# A make-like build utility for Ruby.
gem 'rake'

# A Ruby gem to load environment variables from `.env`.
gem 'dotenv'

# Build a persistent domain model by mapping database tables to Ruby classes.
gem 'activerecord'

# An easy to use but powerful templating system for Ruby
gem 'erb'

# This module provides a Ruby interface for data serialization in YAML format.
gem 'yaml'

# A simple, standardized way to build and use Service Objects in Ruby
gem 'simple_command'

# A Ruby client library for Apache Kafka
gem 'ruby-kafka'